# Generated by Django 6.0.1 on 2026-01-09 09:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=2)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_e164', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('preferred_language', models.CharField(default='en', max_length=20)),
                ('source', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('default_timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('default_language', models.CharField(default='en', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('destination_country_code', models.CharField(max_length=2)),
                ('application_type', models.CharField(choices=[('STUDY', 'Study'), ('WORK', 'Work'), ('VISIT', 'Visit/Tourism'), ('PR', 'Permanent Residency'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('current_status', models.CharField(choices=[('NEW_INQUIRY', 'New Inquiry'), ('CONSULTATION_COMPLETED', 'Consultation Completed'), ('DOCS_REQUESTED', 'Documents Requested'), ('DOCS_RECEIVED', 'Documents Received'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('EMBASSY_REVIEW', 'Embassy Review'), ('ADDITIONAL_DOCS_REQUESTED', 'Additional Docs Requested'), ('DECISION_RECEIVED', 'Decision Received'), ('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('CLOSED', 'Closed')], db_index=True, default='NEW_INQUIRY', max_length=40)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=10)),
                ('last_client_update_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='crm.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='crm.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='crm.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('PHOTO', 'Photo'), ('BANK_STATEMENT', 'Bank Statement'), ('SOP', 'Statement of Purpose'), ('ADMISSION_LETTER', 'Admission Letter'), ('MEDICAL', 'Medical'), ('POLICE_CLEARANCE', 'Police Clearance'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='case_documents/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.case')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='crm.organization'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('destination_country_code', models.CharField(max_length=2)),
                ('application_type', models.CharField(choices=[('STUDY', 'Study'), ('WORK', 'Work'), ('VISIT', 'Visit/Tourism'), ('PR', 'Permanent Residency'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('update_sla_days', models.PositiveIntegerField(default=7)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='crm.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='crm.program'),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('NEW_INQUIRY', 'New Inquiry'), ('CONSULTATION_COMPLETED', 'Consultation Completed'), ('DOCS_REQUESTED', 'Documents Requested'), ('DOCS_RECEIVED', 'Documents Received'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('EMBASSY_REVIEW', 'Embassy Review'), ('ADDITIONAL_DOCS_REQUESTED', 'Additional Docs Requested'), ('DECISION_RECEIVED', 'Decision Received'), ('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('CLOSED', 'Closed')], max_length=40)),
                ('new_status', models.CharField(choices=[('NEW_INQUIRY', 'New Inquiry'), ('CONSULTATION_COMPLETED', 'Consultation Completed'), ('DOCS_REQUESTED', 'Documents Requested'), ('DOCS_RECEIVED', 'Documents Received'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('EMBASSY_REVIEW', 'Embassy Review'), ('ADDITIONAL_DOCS_REQUESTED', 'Additional Docs Requested'), ('DECISION_RECEIVED', 'Decision Received'), ('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('CLOSED', 'Closed')], max_length=40)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='crm.case')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['case', 'changed_at'], name='crm_statush_case_id_ba9557_idx')],
            },
        ),
    ]
